### ISSUE TITLE
When deleting wallet, the application goes to break points and if continued gets aborted

### ISSUE THREAD

**Issue by satindergrewal** [Meshbits/zcash-ios-wallet#6]
Please check what is the issue with the process of deleting wallet, and help fix it.

**Comment by satindergrewal** [comment]
I noticed that if the application is running without the xcode debugger triggering to run in simulator, means if I manually run the application within simulator, and delete the wallet, the wallet closes itself.

@lastw0nd3r can you please check if it is the intended before and if it's OK to have it that way?
If it is intended behaviour, and if it's OK, then please close this issue.

**Comment by lastw0nd3r** [comment]
Fixed, I will discuss the implementation 1-1 for this.
